name: Deploy API Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: edwinmalihu/jenkins-script/.github/reusable-flyio-deploy@v1
    with:
      app_name: "api-gateway-edwin" # use underscore
      config_file: "api-gateway.toml" # use underscore
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      # PAT_TOKEN: ${{ secrets.YOUR_PAT_TOKEN }} # Jika perlu
